namespace api.Enums
{
    public enum TagName
    {
        DESIGN,
        ARRAYS,
        LINKED_LIST,
        SLIDING_WINDOW,
        HASH_TABLE,
        TREE,
        BINARY_SEARCH,
        COUNTING,
        BACKTRACKING,
        MERGE_SORT,
        SORTING,
        TWO_POINTERS,
        STACK,
        QUEUE,
        RECURSION,
        BINARY_SEARCH_TREE,
        STRING,
        DYNAMIC_PROGRAMMING,
        MATH,
        GREEDY,
        GRAPH,
        HEAP,
        PREFIX_SUM,
        ORDERED_SET
    }
}
